---
# tasks file for ansible-role-pywarden
- name: Copy template file
  ansible.builtin.template:
    src: pywarden_config.yaml.j2
    dest: "/home/{{ ansible_user_id }}/pywarden_config.yaml"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0600
    remote_src: false
  delegate_to: localhost

- name: Ensure python3-pip is installed
  ansible.builtin.package:
    name: python3-pip
    state: present
  become: true
  delegate_to: localhost

- name: Ensure pip3 is upgraded
  ansible.builtin.pip:
    name: pip
    extra_args: --upgrade
  delegate_to: localhost

- name: Ensure pywarden is installed
  ansible.builtin.pip:
    name: PyWarden
    extra_args: --upgrade
  delegate_to: localhost

- name: Create Organization Collections
  ansible.builtin.shell:
    cmd: pywarden --add-org-collection --name "{{ item.name }}" --access-group "{{ item.access_group }}"
  with_items: "{{ pywarden_org_items }}"
  delegate_to: localhost

- name: Create Organization Items
  ansible.builtin.shell:
    cmd: pywarden --add-org-entry --name "{{ item.name }}" --username "{{ item.username }}" --password "{{ item.password }}" --url "{{ item.url }}" --org-collection "{{ item.org_collection }}" --access-group "{{ item.access_group }}"
  with_items: "{{ pywarden_org_items }}"
  delegate_to: localhost
